export const TEAMS = [
    { id: 'UAE', name: 'UAE', logo: '/teams/ae.svg' },
    { id: 'AFG', name: 'Afghanistan', logo: '/teams/af.svg' },
    { id: 'AUS', name: 'Australia', logo: '/teams/au.svg' },
    { id: 'CAN', name: 'Cananda', logo: '/teams/ca.svg' },
    { id: 'ENG', name: 'England', logo: '/teams/gb-eng.svg' },
    { id: 'NZ', name: 'New Zealand', logo: '/teams/nz.svg' },
    { id: 'ZIM', name: 'Zimbabwe', logo: '/teams/zw.svg' },
    { id: 'SCO', name: 'Scotland', logo: '/teams/gb-sct.svg' },
    { id: 'IE', name: 'Ireland', logo: '/teams/ie.svg' },
    { id: 'IND', name: 'India', logo: '/teams/in.svg' },
    { id: 'IT', name: 'Itlay', logo: '/teams/it.svg' },
    { id: 'WI', name: 'West Indies', logo: '/teams/windies.jpg' },
    { id: 'NA', name: 'Namibia', logo: '/teams/na.svg' },
    { id: 'NL', name: 'Netherlands', logo: '/teams/nl.svg' },
    { id: 'NP', name: 'Nepal', logo: '/teams/np.svg' },
    { id: 'SA', name: 'South Africa', logo: '/teams/za.svg' },
    { id: 'OM', name: 'Oman', logo: '/teams/om.svg' },
    { id: 'PAK', name: 'Pakistan', logo: '/teams/pk.svg' },
    { id: 'SL', name: 'Sri Lanka', logo: '/teams/sl.svg' },
    { id: 'US', name: 'USA', logo: '/teams/us.svg' },
]
